name = "ImportAll"
uuid = "c65182e5-40f4-518f-8165-175b85689199"
authors = ["Nicholas Timmons <ngtimmons@gmail.com>"]
version = "1.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
